apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - init-configmap.yaml
  - secret.yaml
  - pvc.yaml
  - statefulset.yaml
  - service.yaml
  - migration-job.yaml
